fixed pre-commit disabled  https://github.com/s-weigand/docformatter because leading to an error
```
pre-commit run --all-files
[INFO] Initializing environment for https://github.com/s-weigand/docformatter.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '1ec30b7')
return code: 1
stdout: (none)
stderr:
    error: pathspec '1ec30b7' did not match any file(s) known to git
Check the log at /home/myuser/.cache/pre-commit/pre-commit.log
```